version: 2
jobs:
  build:
    working_directory: ~/dwh-core
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run: ./gradlew allDeps -q > deps.txt

      - restore_cache:
          key: dwh-core-{{ checksum "deps.txt" }}

      - run: ./gradlew --continue clean build jacocoFullReport

      - save_cache:
          paths:
            - ~/.gradle
          key: dwh-core-{{ checksum "deps.txt" }}

      - store_test_results:
          path: build/xml-report

      - store_artifacts:
          path: build/reports/allTests
          destination: test

      - store_artifacts:
          path: build/reports/jacoco/jacocoFullReport/html
          destination: coverage
